import type { Metadata } from 'next';

import './globals.css';
import Sidebar from './components/Sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='min-h-screen flex bg-gray-100'>
        <Sidebar />

        <main className='flex-1 p-6 bg-white'>{children}</main>
      </body>
    </html>
  );
}
