import Sidebar from './components/Sidebar';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='min-h-screen flex flex-col lg:flex-row bg-gray-100'>
        <Sidebar />
        <main className='flex-1 p-6 bg-white'>{children}</main>
      </body>
    </html>
  );
}
